trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nodejshelloworld'
  tag: '$(Build.BuildId)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: '$(imageName)'
      dockerfile: './dockerfile'
      containerRegistry: 'acr-docker-registry-sc'
      tags: |
        $(tag)
    displayName: 'Build and Push Docker image'
